config/routes.rb
Bloid::Engine.routes.draw do
  resources :posts, :only => [:index, :show]

  namespace :admin do
    resources :posts
  end

end

app/models/bloid/post.rb
module Bloid
  class Post
    include Mongoid::Document
    include Mongoid::Timestamps

    field :title, :type => String
    field :renderer, :type => String
    field :raw_body, :type => String
    field :html_body, :type => String, :default => ''
    field :tags, :type => Array

    attr_accessible :title, :renderer, :raw_body, :tags

    scope :most_recent_first, order_by(:created_at => 'DESC')
  end
end

app/controllers/bloid/admin/posts_controller.rb
module Bloid
  module Admin
    class PostsController < ApplicationController

      def index
        @posts = Post.most_recent_first
      end

      def show
        @post = Post.find(params[:id])
      end

      def new
        @post = Post.new
      end

      def create
        @post = Post.new(params[:post])
        if @post.save
          flash[:success] = 'Post created'
          redirect_to admin_posts_path
        else
          flash[:error] = 'Could not create post'
          render :new
        end
      end
    end
  end
end

app/controllers/bloid/application_controller.rb
module Bloid
  class ApplicationController < ActionController::Base
  end
end

app/controllers/bloid/posts_controller.rb
module Bloid
  class PostsController < ApplicationController

    def index
      @posts = Post.all
    end

    def show
    end

  end
end

app/helpers/bloid/application_helper.rb
module Bloid
  module ApplicationHelper
  end
end

app/helpers/bloid/posts_helper.rb
module Bloid
  module PostsHelper
  end
end

app/views/bloid/admin/posts/index.html.haml
= link_to 'New Post', new_admin_post_path
%h1 Posts
- @posts.each do |post|
  %h2= post.title
  %p= post.html_body.html_safe

app/views/bloid/admin/posts/new.html.haml
= form_for @post, :url => admin_posts_path do |f|
  = f.label :title
  = f.text_field :title
  %br
  = f.label :raw_body
  = f.text_area :raw_body
  %br
  = f.submit 'Create'

app/views/bloid/posts/index.html.haml
%h1 Posts
- @posts.each do |post|
  %h2= post.title
  %p= post.html_body.html_safe

app/views/layouts/bloid/application.html.haml
!!!
%html
  %head
    %title Bloid
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tags
  %body
    - if flash.present?
      - flash.each_pair do |level, content|
        %div{:class => "flash #{level}"}= content
    = yield